### ISSUE TITLE
如何处理数字及时间字符？

### ISSUE THREAD

**Issue by QuantumLiu** [harveyaot/DianJing#1]
您好！
在做一个类似项目，在分完词后发现有很多时间和数字的word
想到的处理方法是这样的：
无论在training还是predict都将所有数字和时间标注为特殊字符，如果predict的结果有特殊字符则使用者自行替换。

**Comment by harveyaot** [comment]
我先在的做法是，直接依靠jieba 分词的结果，把所有 unique 的 时间和数字都直接转换为 一个 unique 的word. 会做一下过滤，如果这个word 出现的词频很低，则 使用 "\<unk\>" 统一标识。

**Comment by QuantumLiu** [comment]
我现在正在做的方法是在分词前用正则替换所有的日期和数字

**Comment by harveyaot** [comment]
主要看，将来怎么使用想这些日期和数字，如果是很重要的，需要在标题中出现，需要做些更细致的处理。

**Comment by QuantumLiu** [comment]
你好，我在用FLOAT和DATE等特殊字符替换了所有的数字和日期后，导致了FLOAT词频过高，最终生成标题不可读。我正在想其他更好的方式。
谢谢。

**Comment by QuantumLiu** [comment]
根据您的crawl.py我写了一个脚本，再次感谢您的工作。
[toutiaospider.py](https://github.com/QuantumLiu/Neural-Headline-Generator-CN/blob/master/toutiaospider.py)
